# Generated by Django 3.2.5 on 2021-08-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.classificacao')),
                ('anotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.anotacao')),
                ('aspectos_Educacionais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.aspectos_educacionais')),
                ('ciclo_de_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ciclo_de_vida')),
                ('contribuinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.contribuinte')),
                ('direitos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.direitos')),
                ('geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.geral')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.identificador')),
                ('meta_metadados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.meta_metadados')),
                ('metadados_tecnicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.metadados_tecnicos')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.recurso')),
                ('relacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.relacoes')),
                ('requisitos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.requisitos')),
            ],
        ),
    ]
