# Generated by Django 3.2.5 on 2021-08-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
