# Generated by Django 3.2.5 on 2021-08-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210806_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroartigo',
            name='Classificacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.classificacao'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='anotacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.anotacao'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='aspectos_Educacionais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.aspectos_educacionais'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='contribuinte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.contribuinte'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='direitos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.direitos'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='identificador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.identificador'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='metadados_tecnicos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.metadados_tecnicos'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='recurso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.recurso'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='relacoes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.relacoes'),
        ),
        migrations.AlterField(
            model_name='livroartigo',
            name='requisitos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.requisitos'),
        ),
    ]
