# Generated by Django 3.2.5 on 2021-08-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210811_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('cobertura', models.CharField(max_length=30, null=True, verbose_name='Cobertura')),
                ('estrutura', models.CharField(choices=[('1', 'Coleção'), ('2', 'Misturado'), ('3', 'Linear'), ('4', 'Hierárquico'), ('5', 'Em rede'), ('6', 'Ramificado'), ('7', 'Parcelado'), ('8', 'Atômico')], max_length=20, verbose_name='Estrutura')),
                ('nivel_de_agregacao', models.CharField(choices=[('1', 'Menor nivel de agregação'), ('2', 'Coleção de agregação'), ('3', 'a collection of level 2 learning objects'), ('4', 'the largest level of granularity')], max_length=2, verbose_name='Nivel_de_Agregação')),
                ('versao', models.IntegerField(verbose_name='Versao')),
                ('status', models.CharField(choices=[('1', 'Rascunho'), ('2', 'Final'), ('3', 'Revisado'), ('4', 'Indisponivel')], max_length=15, verbose_name='Status')),
                ('datas', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('esquema_de_metadados', models.CharField(max_length=20, verbose_name='Esquema_de_Metadados')),
                ('catalogo', models.CharField(max_length=150, verbose_name='Catalogo')),
                ('entrada', models.DateField(blank=True, null=True, verbose_name='Entrada')),
                ('papel', models.CharField(choices=[('1', 'Autor'), ('2', 'Editor'), ('3', 'Iniciador'), ('4', 'Terminator'), ('5', 'Validador'), ('6', 'Editor'), ('7', 'Designer Gráfico'), ('8', 'Implementador Técnico'), ('9', 'Provedor de conteúdos'), ('10', 'Validador Técnico'), ('11', 'Validador Educacional'), ('12', 'Roteirista'), ('13', 'Designer instrucional')], max_length=15, verbose_name='Papel')),
                ('entidade', models.CharField(max_length=20, verbose_name='Entidade')),
                ('formato', models.CharField(max_length=15, verbose_name='Formato')),
                ('tamanho', models.CharField(max_length=20, verbose_name='Tamanho')),
                ('requisitos', models.CharField(max_length=50, verbose_name='Requisitos')),
                ('localizacao', models.CharField(max_length=50, verbose_name='Localizacao')),
                ('observacoes_de_instalacoes', models.TextField(verbose_name='Observacoes_de_Instalacoes')),
                ('outros_Requisitos_de_Sistema', models.TextField(verbose_name='Outros_Requisitos_de_Sistema')),
                ('duracao', models.TimeField(verbose_name='Duracao')),
                ('tipo', models.CharField(choices=[('OP', 'Operating System'), ('BW', 'Browser')], max_length=15, verbose_name='tipo')),
                ('nome', models.CharField(choices=[('1', 'PC_DOS'), ('2', 'MS-Windows'), ('3', 'MacOS'), ('4', 'Unix'), ('5', 'Multi-OS'), ('6', 'Nenhum')], max_length=20, verbose_name='Nome')),
                ('versao_min', models.CharField(max_length=20, verbose_name='Versao_min')),
                ('versao_max', models.CharField(max_length=20, verbose_name='Versao_max')),
                ('tipo_de_Interatividade', models.CharField(choices=[('1', 'Ativo'), ('2', 'Expositivo'), ('3', 'Misturado'), ('4', 'Indefinido')], max_length=15, verbose_name='Tipo_de_Interatividade')),
                ('tipo_de_recurso_de_aprendizagem', models.CharField(choices=[('1', 'Exercício'), ('2', 'Simulação'), ('3', 'Questionário'), ('4', 'Diagrama'), ('5', 'Figura'), ('6', 'Gráfico'), ('7', 'Índice'), ('8', 'Slide'), ('9', 'Tabela'), ('10', 'Texto narrativo'), ('11', 'Exame'), ('12', 'Experimentar'), ('13', 'Declaração do Problema'), ('14', 'Auto-avaliação')], max_length=20, verbose_name='Tipo_de_recurso_de_aprendizagem')),
                ('nivel_de_interatividade', models.CharField(choices=[('1', 'muito baixo'), ('2', 'baixo'), ('3', 'médio'), ('4', 'Alto'), ('5', 'muito alto')], max_length=20, verbose_name='Nivel_de_interatividade')),
                ('densidade_semantica', models.CharField(choices=[('1', 'muito baixo'), ('2', 'baixo'), ('3', 'médio'), ('4', 'Alto'), ('5', 'muito alto')], max_length=20, verbose_name='Densidade_semântica')),
                ('usuario_final', models.CharField(choices=[('1', 'Professora'), ('2', 'Autor'), ('3', 'Aprendiz'), ('4', 'Gerente')], max_length=20, verbose_name='Usuário_final')),
                ('contexto_de_aprendizagem', models.CharField(choices=[('1', 'Educação primária'), ('2', 'Educação secundária'), ('3', 'Ensino superior'), ('4', 'Ensino superior'), ('5', 'Primeiro Ciclo Universitário'), ('6', 'Segundo Ciclo Universitário'), ('7', 'Pôs Graduação'), ('8', 'Primeiro Ciclo Escola Técnica'), ('9', 'Segundo Ciclo Escola Técnica'), ('10', 'Formação Profissional'), ('11', 'Formação Contínua'), ('12', 'Trainee')], max_length=20, verbose_name='Contexto_de_aprendizagem')),
                ('idade_recomendada', models.CharField(max_length=20, verbose_name='Idade_Recomendada')),
                ('grau_de_dificuldade', models.CharField(choices=[('1', 'muito baixo'), ('2', 'baixo'), ('3', 'médio'), ('4', 'Alto'), ('5', 'muito alto')], max_length=20, verbose_name='Grau_de_dificuldade')),
                ('tempo_de_aprendizado', models.DateTimeField(verbose_name='Tempo_de_aprendizado')),
                ('linguagem', models.CharField(max_length=20, verbose_name='Linguagem')),
                ('custo', models.FloatField(verbose_name='Custo')),
                ('direitos_autorais', models.CharField(max_length=20, verbose_name='Direitos_autorais')),
                ('genero', models.CharField(max_length=20, verbose_name='Gênero')),
                ('recurso', models.CharField(max_length=20, verbose_name='Recurso')),
                ('pessoa', models.CharField(max_length=20, verbose_name='Pessoa')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('finalidade', models.CharField(choices=[('1', 'Disciplina'), ('2', 'Idéia'), ('3', 'Pré-requisito'), ('4', 'Objetivo Educacional'), ('5', 'Restrições de acessibilidade'), ('6', 'Nível educacional'), ('7', 'Nível de habilidade'), ('8', 'Nível de segurança')], max_length=20, verbose_name='finalidade')),
                ('palavras_chave', models.CharField(max_length=50, verbose_name='Palavras Chave')),
            ],
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='Classificacao',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='anotacao',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='aspectos_Educacionais',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='ciclo_de_vida',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='contribuinte',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='direitos',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='geral',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='meta_metadados',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='metadados_tecnicos',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='relacoes',
        ),
        migrations.RemoveField(
            model_name='livroartigo',
            name='requisitos',
        ),
        migrations.DeleteModel(
            name='anotacao',
        ),
        migrations.DeleteModel(
            name='aspectos_Educacionais',
        ),
        migrations.DeleteModel(
            name='ciclo_de_vida',
        ),
        migrations.DeleteModel(
            name='Classificacao',
        ),
        migrations.DeleteModel(
            name='contribuinte',
        ),
        migrations.DeleteModel(
            name='direitos',
        ),
        migrations.DeleteModel(
            name='Geral',
        ),
        migrations.DeleteModel(
            name='identificador',
        ),
        migrations.DeleteModel(
            name='LivroArtigo',
        ),
        migrations.DeleteModel(
            name='meta_metadados',
        ),
        migrations.DeleteModel(
            name='metadados_tecnicos',
        ),
        migrations.DeleteModel(
            name='recurso',
        ),
        migrations.DeleteModel(
            name='relacoes',
        ),
        migrations.DeleteModel(
            name='requisitos',
        ),
    ]
