# Generated by Django 3.2.5 on 2021-08-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210813_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='data',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='entidade',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='ciclo_de_vida_entidade',
            field=models.CharField(default=None, max_length=20, verbose_name='Entidade CV'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='contribuinte_entidade',
            field=models.CharField(default=None, max_length=20, verbose_name='Contribuinte Entidade'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='data_anotacao',
            field=models.DateTimeField(default=None, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='descricao_anotacao',
            field=models.CharField(default=None, max_length=100, verbose_name='Descricao Anotação'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='descricao_aspectos_educacionais',
            field=models.CharField(default=None, max_length=100, verbose_name='Descricao'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='descricao_direitos',
            field=models.CharField(default=None, max_length=100, verbose_name='Descricao'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='descricao_geral',
            field=models.CharField(default=None, max_length=800, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='descricao_recursos',
            field=models.CharField(default=None, max_length=20, verbose_name='Descrição Recursos'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='palavras_chave_clasifi',
            field=models.CharField(default=None, max_length=50, verbose_name='Palavras Chave'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='linguagem',
            field=models.CharField(max_length=15, verbose_name='Linguagem'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='palavras_chave',
            field=models.CharField(default=None, max_length=50, verbose_name='Palavras Chave'),
        ),
    ]
