# Generated by Django 3.2.5 on 2021-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210813_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cobertura',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='descricao_geral',
            field=models.TextField(default=None, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='estrutura',
            field=models.CharField(blank=True, choices=[('1', 'Coleção'), ('2', 'Misturado'), ('3', 'Linear'), ('4', 'Hierárquico'), ('5', 'Em rede'), ('6', 'Ramificado'), ('7', 'Parcelado'), ('8', 'Atômico')], max_length=20, verbose_name='Estrutura'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='observacoes_de_instalacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes_de_Instalacoes'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='outros_Requisitos_de_Sistema',
            field=models.TextField(blank=True, verbose_name='Outros_Requisitos_de_Sistema'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='papel',
            field=models.CharField(blank=True, choices=[('1', 'Autor'), ('2', 'Editor'), ('3', 'Iniciador'), ('4', 'Terminator'), ('5', 'Validador'), ('6', 'Editor'), ('7', 'Designer Gráfico'), ('8', 'Implementador Técnico'), ('9', 'Provedor de conteúdos'), ('10', 'Validador Técnico'), ('11', 'Validador Educacional'), ('12', 'Roteirista'), ('13', 'Designer instrucional')], max_length=15, verbose_name='Papel'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipo',
            field=models.CharField(max_length=15, verbose_name='tipo'),
        ),
    ]
