# Generated by Django 3.2.5 on 2021-08-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_cadastro_data_contribuinte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tempo_de_aprendizado',
            field=models.TimeField(verbose_name='Tempo_de_aprendizado'),
        ),
    ]
